# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

commands: 
  build-code:
    steps:
      - run: go build ./...
  
  run-integration-tests: 
    steps:
      - run: 
           name: Run Integration tests
           command: |
            set +e
            cd /go/src/go-demo/
            mkdir -p test_results/integration
            gotestsum  --format standard-verbose --junitfile test_results/integration/test_run.xml -- ./test_integrations/... --json -v 2>&1 | tee integrationTestResults
            exit 0
      - run: cat /go/src/go-demo/integrationTestResults
      - store_test_results:
          path: /go/src/go-demo/test_results
      - run:  
          name: Check Integration Test results 
          command: |
            grep -q 'FAIL' /go/src/go-demo/integrationTestResults && exit 1
            exit 0
     
jobs:
  build:
    docker:
      # specify the version 
      - image: circleci/golang:1.12-stretch-browsers

    working_directory: /go/src/go-demo
    steps:
      - checkout
      - build-code
      - run-integration-tests 

workflows:
  version: 2
  build_web_tests:
    jobs:
      - build
      
        
          